### ISSUE TITLE
Testing the API

### ISSUE THREAD

**Issue by stanleycyang** [syang019/Beer_Shop#1]
E2E testing / controller / model testing necessary

**Comment by RobAWilkinson** [comment]
I might make http://nightwatchjs.org/ this work, but probably just do protractor and karma

**Comment by stanleycyang** [comment]
Sounds good!

**Comment by RobAWilkinson** [comment]
try out the nightwatch branch, instructions at the bottom of the readme 6b0343e2c84ddc7a4622dd96b097d12e2924183a

**Comment by stanleycyang** [comment]
Will try it out tomorrow morning :+1:
